// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/chapter.dart';
import 'models/serie.dart';
import 'models/volume_index.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 704718345827476885),
    name: 'Chapter',
    lastPropertyId: const obx_int.IdUid(10, 8540174188432278879),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3618094261372661864),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8876555900701545395),
        name: 'serieId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8705338084580982811),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3172288430397896230),
        name: 'number',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 353167940266335955),
        name: 'volume',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4338647635890083508),
        name: 'pagePaths',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1330642781853596065),
        name: 'folderPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2813946330395320075),
        name: 'cbzPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6068414306405061727),
        name: 'lastPageIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8540174188432278879),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1885637212791138004),
    name: 'Serie',
    lastPropertyId: const obx_int.IdUid(13, 4174117914556712025),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1114812125423967324),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1272956606833129508),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2662234846635556449),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 250615523988137514),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7793034402317164009),
        name: 'coverThumbPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7842908299191096113),
        name: 'folderPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8184111387760860757),
        name: 'sourceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7887125803936746769),
        name: 'dexId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4332977718132527549),
        name: 'sourceUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2729428950680956091),
        name: 'kind',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7555683009449110303),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 919129271328746552),
        name: 'recommendationsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4174117914556712025),
        name: 'arcsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2075165117956073161),
    name: 'VolumeIndex',
    lastPropertyId: const obx_int.IdUid(4, 8776457432531196675),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6761962942029312015),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1675442728961065855),
        name: 'dexId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7167069176342511551),
        name: 'data',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8776457432531196675),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 2075165117956073161),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [1368042165252496314],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      9042154562856219029,
      3971701222021102604,
      4355194192970399923,
      4675742755748779102,
      7723826271663382631,
      2641698333413776877,
      6862203170991768850,
      6304195383208381487,
      7953250552548158715,
      2061780594327931380,
      2229578750739235261,
      79413790625313418,
      7192706370775152616,
      4351675091690243619,
      4362026922958768206,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Chapter: obx_int.EntityDefinition<Chapter>(
      model: _entities[0],
      toOneRelations: (Chapter object) => [],
      toManyRelations: (Chapter object) => {},
      getId: (Chapter object) => object.id,
      setId: (Chapter object, int id) {
        object.id = id;
      },
      objectToFB: (Chapter object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final pagePathsOffset = fbb.writeList(
          object.pagePaths.map(fbb.writeString).toList(growable: false),
        );
        final folderPathOffset = fbb.writeString(object.folderPath);
        final cbzPathOffset = object.cbzPath == null
            ? null
            : fbb.writeString(object.cbzPath!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.serieId);
        fbb.addOffset(2, titleOffset);
        fbb.addFloat64(3, object.number);
        fbb.addInt64(4, object.volume);
        fbb.addOffset(5, pagePathsOffset);
        fbb.addOffset(6, folderPathOffset);
        fbb.addOffset(7, cbzPathOffset);
        fbb.addInt64(8, object.lastPageIndex);
        fbb.addInt64(9, object.addedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serieIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final numberParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final volumeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final pagePathsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final folderPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final cbzPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final lastPageIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final object = Chapter(
          id: idParam,
          serieId: serieIdParam,
          title: titleParam,
          number: numberParam,
          volume: volumeParam,
          pagePaths: pagePathsParam,
          folderPath: folderPathParam,
          cbzPath: cbzPathParam,
          lastPageIndex: lastPageIndexParam,
          addedAt: addedAtParam,
        );

        return object;
      },
    ),
    Serie: obx_int.EntityDefinition<Serie>(
      model: _entities[1],
      toOneRelations: (Serie object) => [],
      toManyRelations: (Serie object) => {},
      getId: (Serie object) => object.id,
      setId: (Serie object, int id) {
        object.id = id;
      },
      objectToFB: (Serie object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final categoryOffset = fbb.writeString(object.category);
        final coverThumbPathOffset = object.coverThumbPath == null
            ? null
            : fbb.writeString(object.coverThumbPath!);
        final folderPathOffset = fbb.writeString(object.folderPath);
        final sourceIdOffset = object.sourceId == null
            ? null
            : fbb.writeString(object.sourceId!);
        final dexIdOffset = object.dexId == null
            ? null
            : fbb.writeString(object.dexId!);
        final sourceUrlOffset = object.sourceUrl == null
            ? null
            : fbb.writeString(object.sourceUrl!);
        final kindOffset = fbb.writeString(object.kind);
        final recommendationsJsonOffset = fbb.writeString(
          object.recommendationsJson,
        );
        final arcsJsonOffset = fbb.writeString(object.arcsJson);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, categoryOffset);
        fbb.addOffset(4, coverThumbPathOffset);
        fbb.addOffset(5, folderPathOffset);
        fbb.addOffset(6, sourceIdOffset);
        fbb.addOffset(7, dexIdOffset);
        fbb.addOffset(8, sourceUrlOffset);
        fbb.addOffset(9, kindOffset);
        fbb.addInt64(10, object.addedAt.millisecondsSinceEpoch);
        fbb.addOffset(11, recommendationsJsonOffset);
        fbb.addOffset(12, arcsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final coverThumbPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final folderPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final sourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final dexIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final sourceUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final kindParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final recommendationsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final arcsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object = Serie(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          category: categoryParam,
          coverThumbPath: coverThumbPathParam,
          folderPath: folderPathParam,
          sourceId: sourceIdParam,
          dexId: dexIdParam,
          sourceUrl: sourceUrlParam,
          kind: kindParam,
          recommendationsJson: recommendationsJsonParam,
          arcsJson: arcsJsonParam,
          addedAt: addedAtParam,
        );

        return object;
      },
    ),
    VolumeIndex: obx_int.EntityDefinition<VolumeIndex>(
      model: _entities[2],
      toOneRelations: (VolumeIndex object) => [],
      toManyRelations: (VolumeIndex object) => {},
      getId: (VolumeIndex object) => object.id,
      setId: (VolumeIndex object, int id) {
        object.id = id;
      },
      objectToFB: (VolumeIndex object, fb.Builder fbb) {
        final dexIdOffset = fbb.writeString(object.dexId);
        final dataOffset = fbb.writeString(object.data);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dexIdOffset);
        fbb.addOffset(2, dataOffset);
        fbb.addInt64(3, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dexIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = VolumeIndex(
          id: idParam,
          dexId: dexIdParam,
          data: dataParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Chapter] entity fields to define ObjectBox queries.
class Chapter_ {
  /// See [Chapter.id].
  static final id = obx.QueryIntegerProperty<Chapter>(
    _entities[0].properties[0],
  );

  /// See [Chapter.serieId].
  static final serieId = obx.QueryIntegerProperty<Chapter>(
    _entities[0].properties[1],
  );

  /// See [Chapter.title].
  static final title = obx.QueryStringProperty<Chapter>(
    _entities[0].properties[2],
  );

  /// See [Chapter.number].
  static final number = obx.QueryDoubleProperty<Chapter>(
    _entities[0].properties[3],
  );

  /// See [Chapter.volume].
  static final volume = obx.QueryIntegerProperty<Chapter>(
    _entities[0].properties[4],
  );

  /// See [Chapter.pagePaths].
  static final pagePaths = obx.QueryStringVectorProperty<Chapter>(
    _entities[0].properties[5],
  );

  /// See [Chapter.folderPath].
  static final folderPath = obx.QueryStringProperty<Chapter>(
    _entities[0].properties[6],
  );

  /// See [Chapter.cbzPath].
  static final cbzPath = obx.QueryStringProperty<Chapter>(
    _entities[0].properties[7],
  );

  /// See [Chapter.lastPageIndex].
  static final lastPageIndex = obx.QueryIntegerProperty<Chapter>(
    _entities[0].properties[8],
  );

  /// See [Chapter.addedAt].
  static final addedAt = obx.QueryDateProperty<Chapter>(
    _entities[0].properties[9],
  );
}

/// [Serie] entity fields to define ObjectBox queries.
class Serie_ {
  /// See [Serie.id].
  static final id = obx.QueryIntegerProperty<Serie>(_entities[1].properties[0]);

  /// See [Serie.title].
  static final title = obx.QueryStringProperty<Serie>(
    _entities[1].properties[1],
  );

  /// See [Serie.description].
  static final description = obx.QueryStringProperty<Serie>(
    _entities[1].properties[2],
  );

  /// See [Serie.category].
  static final category = obx.QueryStringProperty<Serie>(
    _entities[1].properties[3],
  );

  /// See [Serie.coverThumbPath].
  static final coverThumbPath = obx.QueryStringProperty<Serie>(
    _entities[1].properties[4],
  );

  /// See [Serie.folderPath].
  static final folderPath = obx.QueryStringProperty<Serie>(
    _entities[1].properties[5],
  );

  /// See [Serie.sourceId].
  static final sourceId = obx.QueryStringProperty<Serie>(
    _entities[1].properties[6],
  );

  /// See [Serie.dexId].
  static final dexId = obx.QueryStringProperty<Serie>(
    _entities[1].properties[7],
  );

  /// See [Serie.sourceUrl].
  static final sourceUrl = obx.QueryStringProperty<Serie>(
    _entities[1].properties[8],
  );

  /// See [Serie.kind].
  static final kind = obx.QueryStringProperty<Serie>(
    _entities[1].properties[9],
  );

  /// See [Serie.addedAt].
  static final addedAt = obx.QueryDateProperty<Serie>(
    _entities[1].properties[10],
  );

  /// See [Serie.recommendationsJson].
  static final recommendationsJson = obx.QueryStringProperty<Serie>(
    _entities[1].properties[11],
  );

  /// See [Serie.arcsJson].
  static final arcsJson = obx.QueryStringProperty<Serie>(
    _entities[1].properties[12],
  );
}

/// [VolumeIndex] entity fields to define ObjectBox queries.
class VolumeIndex_ {
  /// See [VolumeIndex.id].
  static final id = obx.QueryIntegerProperty<VolumeIndex>(
    _entities[2].properties[0],
  );

  /// See [VolumeIndex.dexId].
  static final dexId = obx.QueryStringProperty<VolumeIndex>(
    _entities[2].properties[1],
  );

  /// See [VolumeIndex.data].
  static final data = obx.QueryStringProperty<VolumeIndex>(
    _entities[2].properties[2],
  );

  /// See [VolumeIndex.updatedAt].
  static final updatedAt = obx.QueryDateProperty<VolumeIndex>(
    _entities[2].properties[3],
  );
}
